Merge code to support FIT image in U-Boot
Merged changes to support FIT image and updated configurations for various devices.

diff --git a/diff.patch b/diff.patch
--- a/diff.patch
+++ b/diff.patch
@@ -1,55 +1,84 @@
---- a/uboot-mtk-20230718-09eda825/configs/mt7986_redmi_ax6000_defconfig
-+++ b/uboot-mtk-20230718-09eda825/configs/mt7986_redmi_ax6000_defconfig
-@@ -5,8 +5,6 @@ CONFIG_ARCH_MEDIATEK=y
- CONFIG_TEXT_BASE=0x41e00000
- CONFIG_SYS_MALLOC_F_LEN=0x4000
- CONFIG_NR_DRAM_BANKS=1
--CONFIG_ENV_SIZE=0x10000
--CONFIG_ENV_OFFSET=0x0
- CONFIG_DEFAULT_DEVICE_TREE="mt7986a-redmi-ax6000"
- CONFIG_SYS_PROMPT="MT7986> "
- CONFIG_TARGET_MT7986=y
-@@ -21,7 +19,6 @@ CONFIG_MTK_WEB_FAILSAFE_AFTER_BOOT_FAILURE=y
- CONFIG_MTK_UBI_SUPPORT=y
- CONFIG_MTK_UPGRADE_BL2_VERIFY=y
- # CONFIG_MTK_UPGRADE_IMAGE_VERIFY is not set
--CONFIG_ENABLE_NAND_NMBM=y
- CONFIG_FIT=y
- CONFIG_AUTOBOOT_MENU_SHOW=y
- CONFIG_AUTOBOOT_MENU_MTK_SHOW=y
-@@ -44,24 +41,26 @@ CONFIG_CMD_GPIO=y
- CONFIG_CMD_GPIO_READ=y
- CONFIG_CMD_MMC=y
- CONFIG_CMD_MTD=y
--CONFIG_CMD_NMBM=y
- CONFIG_CMD_TFTPPUT=y
- CONFIG_CMD_PING=y
- CONFIG_CMD_SMC=y
- CONFIG_CMD_MTDPARTS=y
--CONFIG_MTDIDS_DEFAULT="nmbm0=nmbm0"
--CONFIG_MTDPARTS_DEFAULT="nmbm0:1024k(bl2),256k(Nvram),256k(Bdata),2048k(factory),2048k(fip),256k(crash),256k(crash_log),112640k(ubi)"
-+CONFIG_MTDIDS_DEFAULT="spi-nand0=spi-nand0"
-+CONFIG_MTDPARTS_DEFAULT="spi-nand0:1024k(bl2),256k(Nvram),256k(Bdata),2048k(factory),2048k(fip),125440k(ubi)"
- CONFIG_CMD_GL_BTN=y
- CONFIG_DOS_PARTITION=y
- CONFIG_EFI_PARTITION=y
- CONFIG_PARTITION_TYPE_GUID=y
- CONFIG_OF_EMBED=y
- CONFIG_ENV_OVERWRITE=y
--CONFIG_ENV_IS_IN_MTD=y
--CONFIG_ENV_MTD_NAME="Nvram"
--CONFIG_ENV_SIZE_REDUND=0x80000
-+CONFIG_ENV_IS_IN_UBI=y
-+CONFIG_SYS_REDUNDAND_ENVIRONMENT=y
-+CONFIG_ENV_UBI_PART="ubi"
-+CONFIG_ENV_UBI_VOLUME="ubootenv"
-+CONFIG_ENV_UBI_VOLUME_REDUND="ubootenv2"
- CONFIG_ENV_VARS_UBOOT_RUNTIME_CONFIG=y
- CONFIG_NET_RANDOM_ETHADDR=y
-+CONFIG_NET_FORCE_IPADDR=y
- CONFIG_USE_IPADDR=y
- CONFIG_IPADDR="192.168.1.1"
- CONFIG_USE_NETMASK=y
+From 51605f2382f4eeb08f70b29e45e9b3feac24cd96 Mon Sep 17 00:00:00 2001
+From: 1715173329
+Date: Sat, 27 Dec 2025 23:22:22 +0800
+Subject: [PATCH] uboot-2022: fit: merge code from 1715173329 to support fit
+ image
+
+---
+ .../configs/mt7981_360t7_defconfig            |  3 ++-
+ .../configs/mt7981_abt_asr3000_defconfig      |  3 ++-
+ .../configs/mt7981_ax3000t_defconfig          |  3 ++-
+ .../configs/mt7981_cetron_ct3003_defconfig    |  3 ++-
+ .../configs/mt7981_cmcc_a10_defconfig         |  3 ++-
+ .../configs/mt7981_cmcc_rax3000m_defconfig    |  3 ++-
+ .../configs/mt7981_cudy_tr3000-v1_defconfig   |  1 +
+ .../mt7981_h3c_magic-nx30-pro_defconfig       |  3 ++-
+ .../configs/mt7981_imou_lc-hx3001_defconfig   |  3 ++-
+ .../configs/mt7981_jcg_q30_defconfig          |  3 ++-
+ .../configs/mt7981_konka_komi-a31_defconfig   |  3 ++-
+ .../configs/mt7981_livinet_zr-3020_defconfig  |  3 ++-
+ .../configs/mt7981_nokia_ea0326gmp_defconfig  |  3 ++-
+ .../configs/mt7981_wr30u_defconfig            |  3 ++-
+ .../configs/mt7986_netcore_n60-pro_defconfig  |  3 ++-
+ .../configs/mt7986_netcore_n60_defconfig      |  3 ++-
+ .../configs/mt7986_redmi_ax6000_defconfig     |  3 ++-
+ .../configs/mt7981_360t7_defconfig            |  1 +
+ .../configs/mt7981_abt_asr3000_defconfig      |  1 +
+ .../configs/mt7981_ax3000t_defconfig          |  1 +
+ .../configs/mt7981_cetron_ct3003_defconfig    |  1 +
+ .../configs/mt7981_cmcc_a10_defconfig         |  1 +
+ .../configs/mt7981_cmcc_rax3000m_defconfig    |  1 +
+ .../configs/mt7981_cudy_tr3000-v1_defconfig   |  1 +
+ .../mt7981_h3c_magic-nx30-pro_defconfig       |  1 +
+ .../configs/mt7981_imou_lc-hx3001_defconfig   |  1 +
+ .../configs/mt7981_jcg_q30_defconfig          |  1 +
+ .../configs/mt7981_konka_komi-a31_defconfig   |  1 +
+ .../configs/mt7981_livinet_zr-3020_defconfig  |  1 +
+ .../configs/mt7981_nokia_ea0326gmp_defconfig  |  1 +
+ .../configs/mt7981_wr30u_defconfig            |  1 +
+ .../configs/mt7986_netcore_n60-pro_defconfig  |  1 +
+ .../configs/mt7986_netcore_n60_defconfig      |  1 +
+ .../configs/mt7986_redmi_ax6000_defconfig     |  1 +
+ build.sh                                      |  1 +
+ .../arch/arm/dts/mt7981-abt_asr3000.dts       |  4 ++++
+ .../arch/arm/dts/mt7981-cetron_ct3003.dts     |  4 ++++
+ .../arm/dts/mt7981-cmcc-rax3000m-emmc.dts     |  5 +++++
+ .../arch/arm/dts/mt7981-cmcc-rax3000m.dts     |  4 ++++
+ .../arch/arm/dts/mt7981-konka_komi-a31.dts    |  2 +-
+ .../arch/arm/dts/mt7981-livinet_zr-3020.dts   |  4 ++++
+ .../arch/arm/dts/mt7981-nokia-ea0326gmp.dts   |  4 ++++
+ .../arch/arm/dts/mt7986a-jdcloud_re-cp-03.dts |  4 ++++
+ .../board/mediatek/common/ubi_helper.c        |  4 ++--
+ .../board/mediatek/mt7622/bootmenu_emmc.c     |  4 ++--
+ .../board/mediatek/mt7981/bootmenu_emmc.c     |  4 ++--
+ .../board/mediatek/mt7986/bootmenu_emmc.c     |  4 ++--
+ .../board/mediatek/mt7988/bootmenu_emmc.c     |  4 ++--
+ .../configs/mt7981_360t7_defconfig            | 17 +++++++-------
+ .../configs/mt7981_abt_asr3000_defconfig      | 17 ++++++++------
+ .../configs/mt7981_ax3000t_an8855_defconfig   | 17 ++++++--------
+ .../configs/mt7981_ax3000t_defconfig          | 17 ++++++--------
+ .../configs/mt7981_cetron_ct3003_defconfig    | 19 ++++++++--------
+ .../configs/mt7981_cmcc_a10_defconfig         | 22 +++++++++----------
+ .../mt7981_cmcc_rax3000m-emmc_defconfig       |  6 ++++-
+ .../configs/mt7981_cmcc_rax3000m_defconfig    | 20 +++++++++--------
+ .../configs/mt7981_cudy_tr3000-v1_defconfig   | 16 +++++++-------
+ .../mt7981_h3c_magic-nx30-pro_defconfig       | 17 +++++++-------
+ .../configs/mt7981_imou_lc-hx3001_defconfig   | 18 +++++++--------
+ .../configs/mt7981_jcg_q30_defconfig          | 17 +++++++-------
+ .../configs/mt7981_konka_komi-a31_defconfig   | 19 ++++++++--------
+ .../configs/mt7981_livinet_zr-3020_defconfig  | 19 ++++++++--------
+ .../configs/mt7981_nokia_ea0326gmp_defconfig  | 19 ++++++++--------
+ .../configs/mt7981_wr30u_defconfig            | 18 +++++++--------
+ .../configs/mt7986_jdcloud_re-cp-03_defconfig |  5 ++++-
+ .../configs/mt7986_netcore_n60-pro_defconfig  | 17 +++++++-------
+ .../configs/mt7986_netcore_n60_defconfig      | 17 +++++++-------
+ .../configs/mt7986_redmi_ax6000_defconfig     | 17 +++++++-------
+ .../mt7986_tplink_tl-xdr608x_defconfig        | 13 ++++++-----
+ .../mt7986_tplink_tl-xtr8488_defconfig        |  8 +++++++
+ 70 files changed, 274 insertions(+), 199 deletions(-)
+
+diff --git a/atf-20220606-637ba581b/configs/mt7981_360t7_defconfig b/atf-20220606-637ba581b/configs/mt7981_360t7_defconfig
+index 6378231f5..2d6d7170c 100644
 --- a/atf-20220606-637ba581b/configs/mt7981_360t7_defconfig
 +++ b/atf-20220606-637ba581b/configs/mt7981_360t7_defconfig
 @@ -1,5 +1,6 @@
@@ -400,6 +429,18 @@ index d6210b619..61359e362 100644
  _DRAM_DDR4=y
  _LOG_LEVEL_INFO=y
 +_NAND_SKIP_BAD=y
+diff --git a/build.sh b/build.sh
+index 58587117d..a160fe8f1 100755
+--- a/build.sh
++++ b/build.sh
+@@ -220,6 +220,7 @@ if [ "$FSTHEME" = "mtk" ] || [ "$FSTHEME" = "MTK" ]; then
+ 	echo "CONFIG_WEBUI_FAILSAFE_UI_MTK=y" >> "$UBOOT_DIR/.config"
+ fi
+ 
++grep -q "CONFIG_ENV_VARS_UBOOT_CONFIG=y" "$UBOOT_DIR/.config" || echo "CONFIG_ENV_VARS_UBOOT_CONFIG=y" >> "$UBOOT_DIR/.config"
+ make -C "$UBOOT_DIR" olddefconfig
+ make -C "$UBOOT_DIR" clean
+ make -C "$UBOOT_DIR" -j $(nproc) all
 diff --git a/uboot-mtk-20220606/arch/arm/dts/mt7981-abt_asr3000.dts b/uboot-mtk-20220606/arch/arm/dts/mt7981-abt_asr3000.dts
 index 0ac936faf..c328a98cc 100644
 --- a/uboot-mtk-20220606/arch/arm/dts/mt7981-abt_asr3000.dts
@@ -1699,197 +1740,3 @@ index 71996bf43..2f9dd070e 100644
  CONFIG_BUTTON=y
 -- 
 2.34.1
---- a/uboot-mtk-20230718-09eda825/cmd/glbtn.c
-+++ b/uboot-mtk-20230718-09eda825/cmd/glbtn.c
-@@ -49,8 +49,14 @@
- static int do_glbtn(struct cmd_tbl *cmdtp, int flag, int argc, char *const argv[])
- {
- 	const char *button_label = NULL;
--	int ret, counter = 0;
--	struct udevice *dev;
-+	char buttons[128];
-+	char *name;
-+	struct udevice *dev[2];
-+	int btn_count = 0;
-+	int ret;
-+	int counter = 0;
-+	int i;
-+	int pressed;
- 	ulong ts;
-
- 	led_control("ledblink", "blink_led", "250");
-@@ -58,34 +64,70 @@
- 	gpio_power_clr();
-
- 	button_label = env_get("glbtn_key");
- 	if (!button_label)
--		button_label = "reset";
-+		button_label = "reset,mesh";
-+
-+	strncpy(buttons, button_label, sizeof(buttons) - 1);
-+	buttons[sizeof(buttons) - 1] = '\0';
-+
-+	name = strtok(buttons, ",");
-+
-+	while (name && btn_count < 2) {
-+
-+		ret = button_get_by_label(name, &dev[btn_count]);
-+
-+		if (!ret)
-+			btn_count++;
-+
-+		name = strtok(NULL, ",");
-+	}
-
--	ret = button_get_by_label(button_label, &dev);
--	if (ret) {
--		printf("Button '%s' not found (err=%d)\n", button_label, ret);
-+	if (!btn_count) {
-+		printf("Buttons '%s' not found\n", button_label);
- 		return CMD_RET_FAILURE;
- 	}
-
--	if (!button_get_state(dev)) {
-+	pressed = 0;
-+
-+	for (i = 0; i < btn_count; i++) {
-+		if (button_get_state(dev[i])) {
-+			pressed = 1;
-+			break;
-+		}
-+	}
-+
-+	if (!pressed) {
- 		poller_async_register(&led_p, "led_pa");
- 		poller_call_async(&led_p, 1000000, led_action_post, NULL);
- 		return CMD_RET_SUCCESS;
- 	}
-
- 	led_control("ledblink", "blink_led", "500");
-
--	printf("RESET button is pressed for: %2d second(s)", counter++);
-+	printf("BUTTON is pressed for: %2d second(s)", counter++);
-
- 	ts = get_timer(0);
-
--	while (button_get_state(dev) && counter < 4) {
-+	while (counter < 4) {
-+
-+		pressed = 0;
-+
-+		for (i = 0; i < btn_count; i++) {
-+			if (button_get_state(dev[i])) {
-+				pressed = 1;
-+				break;
-+			}
-+		}
-+
-+		if (!pressed)
-+			break;
-+
- 		if (get_timer(ts) < 1000)
- 			continue;
-
- 		ts = get_timer(0);
-
- 		printf("\b\b\b\b\b\b\b\b\b\b\b\b%2d second(s)", counter++);
- 	}
-
- 	printf("\n");
---- a/uboot-mtk-20220606/cmd/glbtn.c
-+++ b/uboot-mtk-20220606/cmd/glbtn.c
-@@ -49,8 +49,14 @@
- static int do_glbtn(struct cmd_tbl *cmdtp, int flag, int argc, char *const argv[])
- {
- 	const char *button_label = NULL;
--	int ret, counter = 0;
--	struct udevice *dev;
-+	char buttons[128];
-+	char *name;
-+	struct udevice *dev[2];
-+	int btn_count = 0;
-+	int ret;
-+	int counter = 0;
-+	int i;
-+	int pressed;
- 	ulong ts;
-
- 	led_control("ledblink", "blink_led", "250");
-@@ -58,34 +64,70 @@
- 	gpio_power_clr();
-
- 	button_label = env_get("glbtn_key");
- 	if (!button_label)
--		button_label = "reset";
-+		button_label = "reset,mesh";
-+
-+	strncpy(buttons, button_label, sizeof(buttons) - 1);
-+	buttons[sizeof(buttons) - 1] = '\0';
-+
-+	name = strtok(buttons, ",");
-+
-+	while (name && btn_count < 2) {
-+
-+		ret = button_get_by_label(name, &dev[btn_count]);
-+
-+		if (!ret)
-+			btn_count++;
-+
-+		name = strtok(NULL, ",");
-+	}
-
--	ret = button_get_by_label(button_label, &dev);
--	if (ret) {
--		printf("Button '%s' not found (err=%d)\n", button_label, ret);
-+	if (!btn_count) {
-+		printf("Buttons '%s' not found\n", button_label);
- 		return CMD_RET_FAILURE;
- 	}
-
--	if (!button_get_state(dev)) {
-+	pressed = 0;
-+
-+	for (i = 0; i < btn_count; i++) {
-+		if (button_get_state(dev[i])) {
-+			pressed = 1;
-+			break;
-+		}
-+	}
-+
-+	if (!pressed) {
- 		poller_async_register(&led_p, "led_pa");
- 		poller_call_async(&led_p, 1000000, led_action_post, NULL);
- 		return CMD_RET_SUCCESS;
- 	}
-
- 	led_control("ledblink", "blink_led", "500");
-
--	printf("RESET button is pressed for: %2d second(s)", counter++);
-+	printf("BUTTON is pressed for: %2d second(s)", counter++);
-
- 	ts = get_timer(0);
-
--	while (button_get_state(dev) && counter < 4) {
-+	while (counter < 4) {
-+
-+		pressed = 0;
-+
-+		for (i = 0; i < btn_count; i++) {
-+			if (button_get_state(dev[i])) {
-+				pressed = 1;
-+				break;
-+			}
-+		}
-+
-+		if (!pressed)
-+			break;
-+
- 		if (get_timer(ts) < 1000)
- 			continue;
-
- 		ts = get_timer(0);
-
- 		printf("\b\b\b\b\b\b\b\b\b\b\b\b%2d second(s)", counter++);
- 	}
-
- 	printf("\n");
